### ISSUE TITLE
Adjoint of DiffEqArray fails

### ISSUE THREAD

**Issue by omalled** [SciML/DiffEqSensitivity.jl#238] opened 2020-05-08 03:42 UTC
A minor tweak to one of the examples [here](https://docs.sciml.ai/latest/analysis/sensitivity/) gives me an error. Here's the code I am running:

```julia
using DiffEqSensitivity, OrdinaryDiffEq, Zygote
function fiip(du,u,p,t)
  du[1] = dx = p[1]*u[1] - p[2]*u[1]*u[2]
  du[2] = dy = -p[3]*u[2] + p[4]*u[1]*u[2]
end
p = [1.5,1.0,3.0,1.0]; u0 = [1.0;1.0]
prob = ODEProblem(fiip,u0,(0.0,10.0),p)
sol = concrete_solve(prob,Tsit5())
#next line is from https://docs.sciml.ai/latest/analysis/sensitivity/ and works fine
Zygote.gradient((u0,p)->sum(concrete_solve(prob,Tsit5(),u0,p,saveat=0.1,sensealg=QuadratureAdjoint())),u0,p)
#replace the sum with an array access and it gives very verbose error
Zygote.gradient((u0,p)->concrete_solve(prob,Tsit5(),u0,p,saveat=0.1,sensealg=QuadratureAdjoint())[1][1],u0,p)
```

The last line gives an error with a very long stack trace. I can give the full stack trace if that will help, but here's the beginning of it:
```
ERROR: MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type Float64
Closest candidates are:
  convert(::Type{R}, ::T) where {R<:Real, T<:ReverseDiff.TrackedReal} at /Users/omalled/.julia/packages/ReverseDiff/uy0uk/src/tracked.jl:251
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  ...
Stacktrace:
 [1] setindex!(::Array{Float64,1}, ::Array{Float64,1}, ::Int64) at ./array.jl:825
 [2] setindex! at ./subarray.jl:301 [inlined]
 [3] macro expansion at ./broadcast.jl:910 [inlined]
 [4] macro expansion at ./simdloop.jl:77 [inlined]
 [5] copyto! at ./broadcast.jl:909 [inlined]
 [6] copyto! at ./broadcast.jl:864 [inlined]
 [7] materialize! at ./broadcast.jl:823 [inlined]
 [8] (::DiffEqSensitivity.var"#df#78"{Array{Array{Float64,1},1},Array{Float64,1}})(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64) at /Users/omalled/.julia/packages/DiffEqSensitivity/ykcWV/src/local_sensitivity/concrete_solve.jl:68
```

I would expect the above code to work. Should it work, or am I missing something?

**Comment by ChrisRackauckas** [comment] 2020-05-08 04:18
Duplicate of https://github.com/SciML/DiffEqFlux.jl/issues/160

**Comment by ChrisRackauckas** [comment] 2020-05-08 04:19
The workaround is to always do `Array(concrete_solve(...))`, but indeed I would like to get this fixed.

**Comment by omalled** [comment] 2020-05-08 04:24
Thanks for the extremely quick response! The workaround works for me.

**Comment by ChrisRackauckas** [comment] 2020-05-09 20:50
Fixed https://github.com/SciML/DiffEqSensitivity.jl/pull/220

**Closed by ChrisRackauckas** 2020-05-09 20:50 UTC
