### ISSUE TITLE
Differentiating towards a subset of parameters

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqSensitivity.jl#395] opened 2021-03-08 10:18 UTC
```jl
using DiffEqSensitivity
using OrdinaryDiffEq

using FiniteDiff
using Zygote
using ForwardDiff

u0 = [1.0,1.0]
p = [1.5,1.0,3.0,1.0]
function fiip(du,u,p,t)
    if t == 0.0
        println("u in solve ", u, "\n")
        println("p in solve ",p,"\n")
    end
    du[1] = dx = p[1]*u[1] - p[2]*u[1]*u[2]
    du[2] = dy = -p[3]*u[2] + p[4]*u[1]*u[2]
end

prob = ODEProblem(fiip,u0,(0.0,10.0),[1.5,1.0,3.0,1.0],reltol = 1e-9)  
function cost(p1)
    println("p before prob ",vcat(p1,p[2:end]),"\n")
    _prob = remake(prob,p=vcat(p1,p[2:end]))
    println("p before solve ",_prob.p,"\n")
    println("u before solve ",_prob.u0,"\n")
    sol = solve(_prob,Tsit5(),sensealg=ForwardDiffSensitivity(),saveat=0.1)
    sum(sol)
end
FiniteDiff.finite_difference_derivative(cost,p[1]) #  8.305557728239275
ForwardDiff.derivative(cost,p[1]) # 8.305305252400714 # only 1 dual number
Zygote.gradient(cost,p[1]) # (8.305266428305409,) # 4 dual numbers

function cost(p1)
    println("p before prob ",vcat(p1,p[2:end]),"\n")
    _prob = remake(prob,p=vcat(p1,p[2:end]))
    println("p before solve ",_prob.p,"\n")
    println("u before solve ",_prob.u0,"\n")
    sol = solve(_prob,Tsit5(),sensealg=ForwardSensitivity(),saveat=0.1)
    sum(sol)
end
Zygote.gradient(cost,p[1]) # (7.720368430265481,)
```

**Comment by ChrisRackauckas** [comment] 2021-03-14 06:20
This is just a tolerance issue.

```julia
function cost(p1)
    println("p before prob ",vcat(p1,p[2:end]),"\n")
    _prob = remake(prob,p=vcat(p1,p[2:end]))
    println("p before solve ",_prob.p,"\n")
    println("u before solve ",_prob.u0,"\n")
    sol = solve(_prob,Tsit5(),sensealg=ForwardSensitivity(),reltol = 1e-9,saveat=0.1)
    sum(sol)
end
Zygote.gradient(cost,p[1]) # (8.305267160760952,)
```

works fine. The issue is that at such a high tolerance, all 3 of the methods you chose before were very similar. ForwardSensitivity intrinsically uses a different norm because of its expanded system, and this caused it to be different, to tolerance. Making its solving tolerance =1e-9 drops it to the save value.

But the real issue then, why is the tolerance being dropped, is fixed in https://github.com/SciML/DiffEqSensitivity.jl/pull/397

**Closed** 2021-03-14 07:23 UTC
